on: [workflow_dispatch, push]

name: Compass Metrics
description: 'GitHub Action to run Compass metrics commands'

concurrency:
  group: 'compass-metrics-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    name: "Test command to check the action"
    runs-on: ubuntu-latest
    steps:
      - name: Run the "test" command
        uses: thefirstspine-org/github-action-compass-metrics@master
        with:
          command: 'test'
