on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run the "test" command
        id: test
        uses: thefirstspine-org/github-action-compass-metrics@master
        with:
          command: 'test'
      - name: Run the "availability" command
        id: test
        uses: thefirstspine-org/github-action-compass-metrics@master
        with:
          command: 'availability'
          userEmail: ''
          userApiKey: ''
          gatewayDomain: 'thefirstspine.atlassian.net'
          metricSourceId: 'ari:cloud:compass:6ea2c72c-9b15-49d9-bd9d-72a5b6d1b3e1:metric-source/f792fe52-6af8-47ca-9398-ce0c44305c1b/e7709359-fec5-4196-99dd-6db104ffdc2c'
          serviceUrl: 'https://www.thefirstspine.fr'
      - name: Run the "availability" command
        id: test
        uses: thefirstspine-org/github-action-compass-metrics@master
        with:
          command: 'open-vulnerabilities'
          userEmail: ''
          userApiKey: ''
          gatewayDomain: 'thefirstspine.atlassian.net'
          metricSourceId: 'ari:cloud:compass:6ea2c72c-9b15-49d9-bd9d-72a5b6d1b3e1:metric-source/f792fe52-6af8-47ca-9398-ce0c44305c1b/14127aa2-bb0e-4506-9d59-fb8a873be754'
          serviceRepository: 'thefirstspine-org/arena.git'
          scanNpmVulnerabilities: true
          scanDockerVulnerabilities: true
