on: [workflow_dispatch, push]

name: Compass Metrics
description: 'GitHub Action to run Compass metrics commands'

concurrency:
  group: 'compass-metrics-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run the "test" command
        uses: thefirstspine-org/github-action-compass-metrics@master
        with:
          command: 'test'
  availability:
    runs-on: ubuntu-latest
    steps:
      - name: Run the "availability" command
        uses: thefirstspine-org/github-action-compass-metrics@master
        with:
          command: 'availability'
          atlassianUserApiKey: ${{ secrets.ATLASSIAN_USER_EMAIL }}
          atlassianUserEmail: 'teddy@thefirstspine.fr'
          gatewayDomain: 'thefirstspine.atlassian.net'
          metricSourceId: 'ari:cloud:compass:6ea2c72c-9b15-49d9-bd9d-72a5b6d1b3e1:metric-source/f792fe52-6af8-47ca-9398-ce0c44305c1b/e7709359-fec5-4196-99dd-6db104ffdc2c'
          serviceUrl: 'https://www.thefirstspine.fr'
  open-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - name: Run the "availability" command
        uses: thefirstspine-org/github-action-compass-metrics@master
        with:
          command: 'open-vulnerabilities'
          atlassianUserApiKey: ${{ secrets.atlassianUserEmail }}
          atlassianUserEmail: 'teddy@thefirstspine.fr'
          gatewayDomain: 'thefirstspine.atlassian.net'
          metricSourceId: 'ari:cloud:compass:6ea2c72c-9b15-49d9-bd9d-72a5b6d1b3e1:metric-source/f792fe52-6af8-47ca-9398-ce0c44305c1b/14127aa2-bb0e-4506-9d59-fb8a873be754'
          serviceRepository: 'thefirstspine-org/arena.git'
          scanNpmVulnerabilities: true
          scanDockerVulnerabilities: true

