on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run the "test" command
        id: test
        uses: thefirstspine-org/github-action-compass-metrics@master
        with:
          command: 'test'
